name: Build and Deploy to GitHub Pages Repo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Build project with Bun
        run: bun run build

      - name: Clone GitHub Pages repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/talex-tnt/talex-tnt.github.io.git gh-pages-repo
          cd gh-pages-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy build to GitHub Pages repo
        run: |
          rm -rf gh-pages-repo/via-col-vento
          mkdir -p gh-pages-repo/via-col-vento
          cp -r dist/* gh-pages-repo/via-col-vento/

      - name: Commit and push
        run: |
          cd gh-pages-repo
          git add via-col-vento
          git commit -m "Deploy via-col-vento from source [ci skip]" || echo "No changes to commit"
          git push
